# Generated by Django 5.1.7 on 2025-03-11 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pergunta_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_time1', models.IntegerField()),
                ('placar_time2', models.IntegerField()),
                ('data', models.DateField()),
                ('time1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='core.time')),
                ('time2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='core.time')),
            ],
        ),
    ]
